/**
 * Mẫu .gitignore dựng sẵn (rút gọn từ github/gitignore) + hàm gộp nhiều mẫu thành một file.
 * Logic thuần, không phụ thuộc React.
 */

export type GitignoreCategory = 'lang' | 'framework' | 'os' | 'editor' | 'tool';

export interface GitignoreTemplate {
  id: string;
  name: string;
  category: GitignoreCategory;
  /** Đường dẫn trong repo github/gitignore (có thể nhiều file); null nếu không có mẫu chính thức. */
  ghPaths: string[] | null;
  content: string;
}

export const CATEGORY_LABEL: Record<GitignoreCategory, string> = {
  lang: 'Ngôn ngữ',
  framework: 'Framework',
  os: 'Hệ điều hành',
  editor: 'Trình soạn thảo / IDE',
  tool: 'Công cụ',
};

const t = (s: string) => s.replace(/^\n/, '').replace(/\s+$/, '') + '\n';

export const GITIGNORE_TEMPLATES: GitignoreTemplate[] = [
  {
    id: 'node',
    name: 'Node',
    category: 'lang',
    ghPaths: ['Node.gitignore'],
    content: t(`
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage
lib-cov
coverage
*.lcov
.nyc_output

# Dependency directories
node_modules/
jspm_packages/

# TypeScript
*.tsbuildinfo

# Caches
.npm
.eslintcache
.stylelintcache
.node_repl_history
.cache
.parcel-cache

# Packed tarballs
*.tgz

# Yarn
.yarn-integrity
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# dotenv environment files
.env
.env.*
!.env.example

# Build output
dist/
build/
out/

# Serverless / misc
.serverless/
.fusebox/
.dynamodb/
.vuepress/dist
.temp
`),
  },
  {
    id: 'python',
    name: 'Python',
    category: 'lang',
    ghPaths: ['Python.gitignore'],
    content: t(`
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Sphinx documentation
docs/_build/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Type checkers / linters
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.pytype/
.ruff_cache/

# Celery
celerybeat-schedule
celerybeat.pid

# Spyder / Rope
.spyderproject
.spyproject
.ropeproject
`),
  },
  {
    id: 'java',
    name: 'Java',
    category: 'lang',
    ghPaths: ['Java.gitignore'],
    content: t(`
# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Virtual machine crash logs
hs_err_pid*
replay_pid*
`),
  },
  {
    id: 'maven-gradle',
    name: 'Maven / Gradle',
    category: 'tool',
    ghPaths: ['Maven.gitignore', 'Gradle.gitignore'],
    content: t(`
# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle
**/build/
!src/**/build/
gradle-app.setting
!gradle-wrapper.jar
!gradle-wrapper.properties
.gradletasknamecache
`),
  },
  {
    id: 'go',
    name: 'Go',
    category: 'lang',
    ghPaths: ['Go.gitignore'],
    content: t(`
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with \`go test -c\`
*.test

# Output of the go coverage tool
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum

# env file
.env
`),
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'lang',
    ghPaths: ['Rust.gitignore'],
    content: t(`
# Generated by Cargo
debug/
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# Cargo.lock

# MSVC Windows builds of rustc generate these
*.pdb

# RustRover
#.idea/
`),
  },
  {
    id: 'c-cpp',
    name: 'C / C++',
    category: 'lang',
    ghPaths: ['C.gitignore', 'C++.gitignore'],
    content: t(`
# Prerequisites
*.d

# Object files
*.o
*.ko
*.obj
*.elf

# Linker output
*.ilk
*.map
*.exp

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo

# Shared objects (inc. Windows DLLs)
*.dll
*.so
*.so.*
*.dylib

# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex

# Debug files
*.dSYM/
*.su
*.idb
*.pdb

# Kernel Module Compile Results
*.mod*
*.cmd
.tmp_versions/
modules.order
Module.symvers
Mkfile.old
dkms.conf

# C++ modules / debug
*.slo
*.lai
*.gcno
*.gcda

# CMake
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
install_manifest.txt
CTestTestfile.cmake
_deps/
build/
`),
  },
  {
    id: 'dotnet',
    name: 'C# / .NET (Visual Studio)',
    category: 'lang',
    ghPaths: ['VisualStudio.gitignore'],
    content: t(`
# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio cache/options directory
.vs/

# Visual Studio Code
.vscode/

# Test results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*
*.trx
*.VisualState.xml
TestResult.xml
coverage*.json
coverage*.xml
*.coverage
*.coveragexml

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/

# MSBuild / compiler outputs
*_i.c
*_p.c
*_h.h
*.ilk
*.meta
*.obj
*.iobj
*.pch
*.pdb
*.ipdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*_wpftmp.csproj
*.log
*.tlog
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# ReSharper
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user

# NuGet
*.nupkg
*.snupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nuget.props
*.nuget.targets

# Publish
*.[Pp]ublish.xml
*.pubxml
*.publishproj
PublishScripts/

# Azure / Windows Store
csx/
*.build.csdef
AppPackages/
BundleArtifacts/
*.appx
*.msix

# Others
ClientBin/
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.jfm
*.pfx
*.publishsettings
Generated_Code/
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm
*.mdf
*.ldf
*.ndf
`),
  },
  {
    id: 'php',
    name: 'PHP (Composer)',
    category: 'lang',
    ghPaths: ['Composer.gitignore'],
    content: t(`
composer.phar
/vendor/

# Commit your application's lock file https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
# composer.lock

# PHPUnit / tools
.phpunit.result.cache
.phpunit.cache/
.php-cs-fixer.cache
.php_cs.cache
phpunit.xml
.env
`),
  },
  {
    id: 'ruby',
    name: 'Ruby',
    category: 'lang',
    ghPaths: ['Ruby.gitignore'],
    content: t(`
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
.env

# Ignore Byebug command history file.
.byebug_history

# Documentation cache and generated files
/.yardoc/
/_yardoc/
/doc/
/rdoc/

# Environment normalization
/.bundle/
/vendor/bundle
/lib/bundler/man/

# for a library or gem, you might want to ignore these files
# Gemfile.lock
# .ruby-version
# .ruby-gemset

# unless supporting rvm < 1.11.0 or doing something fancy, ignore this
.rvmrc
`),
  },
  {
    id: 'swift',
    name: 'Swift / Xcode',
    category: 'lang',
    ghPaths: ['Swift.gitignore'],
    content: t(`
# Xcode
build/
DerivedData/
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata/
*.xccheckout
*.moved-aside
*.xcuserstate
*.xcscmblueprint
*.hmap
*.ipa
*.dSYM.zip
*.dSYM

## Obj-C/Swift specific
timeline.xctimeline
playground.xcworkspace

# Swift Package Manager
.build/
.swiftpm/
# Packages/
# Package.pins
# Package.resolved

# CocoaPods
Pods/

# Carthage
Carthage/Build/

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots/**/*.png
fastlane/test_output
`),
  },
  {
    id: 'android',
    name: 'Kotlin / Android',
    category: 'lang',
    ghPaths: ['Android.gitignore'],
    content: t(`
# Built application files
*.apk
*.aar
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizardSettings.xml
.idea/dictionaries
.idea/libraries
.idea/caches

# Keystore files
*.jks
*.keystore

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.cxx/

# Google Services (e.g. APIs or Firebase)
google-services.json

# Freeline
freeline.py
freeline/
freeline_project_description.json

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output
fastlane/readme.md

# Version control
vcs.xml

# lint
lint/intermediates/
lint/generated/
lint/outputs/
lint/tmp/

# Kotlin
.kotlin/
`),
  },
  {
    id: 'unity',
    name: 'Unity',
    category: 'tool',
    ghPaths: ['Unity.gitignore'],
    content: t(`
# This .gitignore file should be placed at the root of your Unity project directory
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures can get excessive in size.
/[Mm]emoryCaptures/

# Recordings can get excessive in size
/[Rr]ecordings/

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# Temporary auto-generated Android Assets
/[Aa]ssets/[Ss]treamingAssets/aa.meta
/[Aa]ssets/[Ss]treamingAssets/aa/*
`),
  },
  {
    id: 'dart',
    name: 'Dart / Flutter',
    category: 'lang',
    ghPaths: ['Dart.gitignore'],
    content: t(`
# Files and directories created by pub.
.dart_tool/
.packages
.pub-cache/
.pub/
build/
pubspec.lock

# Flutter / Dart tooling
.flutter-plugins
.flutter-plugins-dependencies
.metadata
.fvm/
flutter_*.png
*.g.dart
*.freezed.dart
coverage/

# Android (Flutter)
**/android/**/gradle-wrapper.jar
**/android/.gradle
**/android/captures/
**/android/gradlew
**/android/gradlew.bat
**/android/local.properties
**/android/**/GeneratedPluginRegistrant.java
**/android/key.properties
*.jks

# iOS (Flutter)
**/ios/**/*.mode1v3
**/ios/**/*.mode2v3
**/ios/**/*.moved-aside
**/ios/**/*.pbxuser
**/ios/**/*.perspectivev3
**/ios/**/*sync/
**/ios/**/.sconsign.dblite
**/ios/**/.tags*
**/ios/**/.vagrant/
**/ios/**/DerivedData/
**/ios/**/Icon?
**/ios/**/Pods/
**/ios/**/.symlinks/
**/ios/**/profile
**/ios/**/xcuserdata
**/ios/.generated/
**/ios/Flutter/.last_build_id
**/ios/Flutter/App.framework
**/ios/Flutter/Flutter.framework
**/ios/Flutter/Flutter.podspec
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/ephemeral
**/ios/Flutter/app.flx
**/ios/Flutter/app.zip
**/ios/Flutter/flutter_assets/
**/ios/Flutter/flutter_export_environment.sh
**/ios/ServiceDefinitions.json
**/ios/Runner/GeneratedPluginRegistrant.*
`),
  },
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'tool',
    ghPaths: ['Terraform.gitignore'],
    content: t(`
# Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all .tfvars files, which are likely to contain sensitive data
*.tfvars
*.tfvars.json

# Ignore override files as they are usually used to override resources locally
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Ignore transient lock info files created by terraform apply
.terraform.tfstate.lock.info

# Ignore CLI configuration files
.terraformrc
terraform.rc
`),
  },
  {
    id: 'macos',
    name: 'macOS',
    category: 'os',
    ghPaths: ['Global/macOS.gitignore'],
    content: t(`
# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \\r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
`),
  },
  {
    id: 'windows',
    name: 'Windows',
    category: 'os',
    ghPaths: ['Global/Windows.gitignore'],
    content: t(`
# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk
`),
  },
  {
    id: 'linux',
    name: 'Linux',
    category: 'os',
    ghPaths: ['Global/Linux.gitignore'],
    content: t(`
*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

# Linux trash folder which might appear on any partition or disk
.Trash-*

# .nfs files are created when an open file is removed but is still being accessed
.nfs*

# KDE directory preferences
.directory
`),
  },
  {
    id: 'jetbrains',
    name: 'JetBrains (IntelliJ, WebStorm, PyCharm...)',
    category: 'editor',
    ghPaths: ['Global/JetBrains.gitignore'],
    content: t(`
# User-specific stuff
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf

# AWS User-specific
.idea/**/aws.xml

# Generated files
.idea/**/contentModel.xml

# Sensitive or high-churn files
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml

# Gradle
.idea/**/gradle.xml
.idea/**/libraries

# CMake
cmake-build-*/

# Mongo Explorer plugin
.idea/**/mongoSettings.xml

# File-based project format
*.iws

# IntelliJ
out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# Editor-based Rest Client
.idea/httpRequests

# Android studio 3.1+ serialized cache file
.idea/caches/build_file_checksums.ser
`),
  },
  {
    id: 'vscode',
    name: 'VisualStudioCode',
    category: 'editor',
    ghPaths: ['Global/VisualStudioCode.gitignore'],
    content: t(`
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History for Visual Studio Code
.history/

# Built Visual Studio Code Extensions
*.vsix
`),
  },
  {
    id: 'vim',
    name: 'Vim',
    category: 'editor',
    ghPaths: ['Global/Vim.gitignore'],
    content: t(`
# Swap
[._]*.s[a-v][a-z]
!*.svg
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]

# Session
Session.vim
Sessionx.vim

# Temporary
.netrwhist
*~

# Auto-generated tag files
tags

# Persistent undo
[._]*.un~
`),
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'framework',
    ghPaths: null,
    content: t(`
# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files (can opt-in for committing if needed)
.env*
!.env.example

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`),
  },
  {
    id: 'react',
    name: 'React (Create React App / Vite)',
    category: 'framework',
    ghPaths: null,
    content: t(`
# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build
/dist

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Vite
*.local
vite.config.js.timestamp-*
vite.config.ts.timestamp-*
`),
  },
  {
    id: 'vue',
    name: 'Vue / Nuxt',
    category: 'framework',
    ghPaths: null,
    content: t(`
node_modules/
dist/
.output/
.nuxt/
.cache/

# Local env files
.env
.env.local
.env.*.local

# Log files
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Vitest / Cypress
coverage/
cypress/videos/
cypress/screenshots/

# TypeScript
*.tsbuildinfo
`),
  },
  {
    id: 'laravel',
    name: 'Laravel',
    category: 'framework',
    ghPaths: ['Laravel.gitignore'],
    content: t(`
/vendor/
node_modules/
npm-debug.log
yarn-error.log

# Laravel 4 specific
bootstrap/compiled.php
app/storage/

# Laravel 5 & Lumen specific
public/storage
public/hot

# Laravel 5 & Lumen specific with changed public path
public_html/storage
public_html/hot

storage/*.key
storage/pail
.env
.env.backup
.env.production
.phpunit.result.cache
Homestead.json
Homestead.yaml
auth.json
/.fleet
/.idea
/.nova
/.vscode
/.zed
`),
  },
  {
    id: 'django',
    name: 'Django',
    category: 'framework',
    ghPaths: null,
    content: t(`
*.log
*.pot
*.pyc
__pycache__/
local_settings.py
db.sqlite3
db.sqlite3-journal
media/

# Static files collected by collectstatic
staticfiles/
static_root/

# Environment
.env
.venv
venv/
`),
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'tool',
    ghPaths: null,
    content: t(`
# Local overrides of compose files
docker-compose.override.yml
compose.override.yaml

# Local data volumes
.docker/
docker-data/

# Secrets / env
.env
*.env.local

# Logs
*.log
`),
  },
  {
    id: 'jekyll',
    name: 'Jekyll',
    category: 'framework',
    ghPaths: ['Jekyll.gitignore'],
    content: t(`
_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata

# Ignore folders generated by Bundler
.bundle/
vendor/
`),
  },
];

export function findTemplate(id: string): GitignoreTemplate | undefined {
  return GITIGNORE_TEMPLATES.find((x) => x.id === id);
}

export type SectionSource = 'builtin' | 'github' | 'builtin-fallback';

export interface GitignoreSection {
  name: string;
  source: SectionSource;
  content: string;
}

export interface MergeResult {
  text: string;
  /** Số dòng mẫu trùng đã bị loại. */
  removed: number;
}

const isPattern = (line: string) => {
  const s = line.trim();
  return s !== '' && !s.startsWith('#');
};

/**
 * Gộp nhiều section thành một file .gitignore, mỗi section có tiêu đề riêng.
 * Dòng pattern trùng khớp hoàn toàn (sau khi trim) với section trước sẽ bị bỏ.
 */
export function mergeGitignore(sections: GitignoreSection[]): MergeResult {
  const seen = new Set<string>();
  let removed = 0;
  const out: string[] = [];

  for (const sec of sections) {
    const lines = sec.content.replace(/\r\n?/g, '\n').split('\n');
    const kept: string[] = [];
    let pending: string[] = [];
    for (const raw of lines) {
      const line = raw.replace(/\s+$/, '');
      if (!isPattern(line)) {
        pending.push(line);
        continue;
      }
      const key = line.trim();
      if (seen.has(key)) {
        removed++;
        // bỏ các dòng chú thích ngay phía trên (không có dòng trống xen giữa)
        while (pending.length && pending[pending.length - 1].trim() !== '') pending.pop();
        continue;
      }
      seen.add(key);
      kept.push(...pending, line);
      pending = [];
    }
    // chú thích đứng riêng ở cuối (nếu có) cũng giữ lại
    const body = [...kept, ...pending.filter((l) => l.trim() !== '' )];
    // gom dòng trống liên tiếp
    const cleaned: string[] = [];
    for (const l of body) {
      if (l.trim() === '' && (cleaned.length === 0 || cleaned[cleaned.length - 1].trim() === '')) continue;
      cleaned.push(l);
    }
    while (cleaned.length && cleaned[cleaned.length - 1].trim() === '') cleaned.pop();
    if (cleaned.length === 0) continue;
    out.push(`# ===== ${sec.name} =====`, ...cleaned, '');
  }

  const text = out.length ? out.join('\n').replace(/\n+$/, '') + '\n' : '';
  return { text, removed };
}

const RAW_BASE = 'https://raw.githubusercontent.com/github/gitignore/main/';

/** Tải mẫu chính thức từ GitHub. Trả về null nếu không có đường dẫn hoặc lỗi mạng. */
export async function fetchOfficialTemplate(
  tpl: GitignoreTemplate,
  signal?: AbortSignal
): Promise<string | null> {
  if (!tpl.ghPaths) return null;
  try {
    const parts: string[] = [];
    for (const p of tpl.ghPaths) {
      const res = await fetch(RAW_BASE + p.split('/').map(encodeURIComponent).join('/'), { signal });
      if (!res.ok) return null;
      const txt = await res.text();
      if (txt.length > 200_000) return null;
      parts.push(txt);
    }
    return parts.join('\n');
  } catch {
    return null;
  }
}
